version: 1
execution:
  poolSize: 3
  maxPoolSize: 5
  queueSize: 100
webserver:
  port: 8080
  workDir: ./data/webserver/
database:
  - name: v1
    path: D:/Projects/p2rank/p2rank-web/data/v1/
    readOnly: true
  - name: v2
    path: ./data/v2/
    readOnly: true
  - name: pdb
    path: ./data/latest-pdb/
    readOnly: false
    allowCustomFiles: false
  - name: user
    path: ./data/latest-user/
    readOnly: false
    allowCustomFiles: true
