version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
      args:
        GOOGLE_ANALYTICS: "UA-136777636-1"
        WEB_SERVICE_USER: ${WEB_SERVICE_USER}
        WEB_SERVICE_PASSWORD: ${WEB_SERVICE_PASSWORD}
    depends_on:
      - web-server
    restart: unless-stopped
    ports:
      - "8020:80"
  web-server:
    build:
      context: ./
      dockerfile: ./web-server/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      CELERY_BROKER_PATH: "/data/prankweb/broker"
      PRANKWEB_DATA: "/data/prankweb"
    restart: unless-stopped
    volumes:
      - predictions:/data/prankweb
  executor:
    build:
      context: ./
      dockerfile: ./executor/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    environment:
      CELERY_BROKER_PATH: "/data/prankweb/broker"
    restart: unless-stopped
    volumes:
      - conservation:/data/conservation
      - predictions:/data/prankweb
  monitor:
    build:
      context: ./
      dockerfile: ./monitor/Dockerfile
    environment:
      GOOGLE_ANALYTICS: "UA-136777636-2"
    restart: unless-stopped
volumes:
  conservation:
    external: True
    name: prankweb_conservation
  predictions:
    external: True
    name: prankweb_predictions
