version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
      labels:
        com.github.cusbg.project: "prankweb"
    restart: unless-stopped
    networks:
      - prankweb
    ports:
      - "8020:80"
  runtime:
    build:
      context: ./
      dockerfile: ./runtime/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        P2RANK_DOWNLOAD_URL: "https://github.com/rdk/p2rank/releases/download/2.3.1/p2rank_2.3.1.tar.gz"
      labels:
        com.github.cusbg.project: "prankweb"
    user: ${UID}:${GID}
    restart: unless-stopped
    networks:
      - prankweb
    volumes:
      - /data/conservation/2020_06:/data/conservation/blast-database
      - /data/conservation/hssp:/data/conservation/hssp
      - /data/prankweb:/data/prankweb/task
networks:
  prankweb:
