version: "3.8"
services:
  p2rank-monitor:
    build:
      context: ./
      dockerfile: ./monitor/Dockerfile
      args:
        USER: ${USER}
    restart: unless-stopped
    networks:
      - p2rank-online
    environment:
      P2RANK_WEB_MONITOR_GOOGLE_ANALYTICS: "UA-136777636-2"
  p2rank-web-runtime:
    build:
      args:
        USER: "1002"
    user: "1002"
    volumes:
      - /data/conservation:/data/conservation
      - /data/p2rank-online:/data/p2rank/task
