version: "3.8"
services:
  prankweb-gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
      labels:
        com.github.cusbg.project: "prankweb"
    restart: unless-stopped
    networks:
      - prankweb
    ports:
      - "8080:80"
  prankweb-runtime:
    build:
      context: ./
      dockerfile: ./runtime/Dockerfile
      args:
        USER: ${USER}
        P2RANK_DOWNLOAD_URL: "https://github.com/rdk/p2rank/releases/download/2.2/p2rank_2.2.tar.gz"
      labels:
        com.github.cusbg.project: "prankweb"
    user: ${USER}
    restart: unless-stopped
    networks:
      - prankweb
    volumes:
      - /data/conservation/blast-database:/data/conservation/blast-database
      - /data/conservation/hssp:/data/conservation/hssp
      - /data/prankweb:/data/p2rank/task
networks:
  prankweb:
