version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
      args:
        GOOGLE_ANALYTICS: ""
    depends_on:
      - rabbitmq
      - api-server
#    restart: unless-stopped
    ports:
      - "8020:80"
  rabbitmq:
    build:
      context: ./
      dockerfile: ./rabbitmq/Dockerfile
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user-develop"
      RABBITMQ_DEFAULT_PASS: "develop"
#    restart: unless-stopped
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia/
  api-server:
    build:
      context: ./
      dockerfile: ./web-server/Dockerfile
      args:
        UID: ${UID-5988}
        GID: ${GID-5988}
    depends_on:
      - rabbitmq
    environment:
      CELERY_BROKER_URL: "amqp://user-develop:develop@rabbitmq:5672"
      PRANKWEB_DATA: "/data/prankweb"
#    restart: unless-stopped
    volumes:
      - predictions:/data/prankweb
  executor:
    build:
      context: ./
      dockerfile: ./executor/Dockerfile
      args:
        UID: ${UID-5988}
        GID: ${GID-5988}
    depends_on:
      - rabbitmq
    environment:
      CELERY_BROKER_URL: "amqp://user-develop:develop@rabbitmq:5672"
#    restart: unless-stopped
    volumes:
      - conservation:/data/conservation
      - predictions:/data/prankweb
volumes:
  rabbitmq:
  conservation:
  predictions:
