version: "3.8"
services:
  gateway:
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
      labels:
        com.github.cusbg.project: "prankweb"
    restart: unless-stopped
    networks:
      - prankweb
    ports:
      - "8020:80"
  runtime:
    build:
      context: ./
      dockerfile: ./runtime/Dockerfile
      args:
        UID: 5988
        GID: 5988
        P2RANK_DOWNLOAD_URL: "https://github.com/rdk/p2rank/releases/download/2.2/p2rank_2.2.tar.gz"
      labels:
        com.github.cusbg.project: "prankweb"
    user: 5988:5988
    restart: unless-stopped
    networks:
      - prankweb
    volumes:
      - conservation-volume:/data/conservation/
      - data-volume:/data/prankweb/task
networks:
  prankweb:
volumes:
  conservation-volume:
  data-volume:
