version: "3.8"
services:
  p2rank-api-gateway:
    ports:
      - "8020:80"
  p2rank-monitor:
    build:
      context: ./
      dockerfile: ./monitor/Dockerfile
      labels:
        com.github.cusbg.project: "p2rank"
    restart: unless-stopped
    networks:
      - p2rank-online
    environment:
      P2RANK_WEB_MONITOR_GOOGLE_ANALYTICS: ""
  p2rank-web-runtime:
    build:
      args:
        USER: "1001"
    user: "1001"
    volumes:
      - /data/conservation:/data/conservation
      - /data/p2rank-online:/data/p2rank/task
